apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret

  labels:
    app: machine-event-store
type: Opaque
stringData:

  mongodb-uri: "mongodb+srv://Anshul:${MONGO_DB_PASSWORD}@shoppingcart.bufa1em.mongodb.net/machine_event_store?retryWrites=true&w=majority"
